name: Create zip
on:
    push:
        tags:
            - '*'

jobs:
    CreateZip:
        runs-on: ubuntu-latest
        container: ghcr.io/friendsofshopware/platform-plugin-dev:v6.3.1
        steps:
            -   name: Get the version
                id: get_version
                run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

            -   name: Checkout
                uses: actions/checkout@v2.3.1
                with:
                    path: RuneLaenenTwoFactorAuth

            -   name: Build & create zip
                run: |
                    cp -r "./RuneLaenenTwoFactorAuth" "/plugins/RuneLaenenTwoFactorAuth"
                    composer install -d "/plugins/RuneLaenenTwoFactorAuth" --no-ansi --no-dev --no-interaction --no-plugins --no-progress --no-scripts --no-suggest --optimize-autoloader --ignore-platform-reqs
                    start-mysql
                    pack-plugin "RuneLaenenTwoFactorAuth"

            -   name: Create Release
                if: startsWith(github.ref, 'refs/tags/')
                id: create_release
                uses: actions/create-release@v1.0.0
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: ${{ steps.get_version.outputs.VERSION }}
                    release_name: ${{ steps.get_version.outputs.VERSION }}
                    draft: false
                    prerelease: false

            -   name: Upload Release Asset
                if: startsWith(github.ref, 'refs/tags/')
                id: upload_release_asset
                uses: actions/upload-release-asset@v1.0.2
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: ${{ steps.create_release.outputs.upload_url }}
                    asset_path: RuneLaenenTwoFactorAuth.zip
                    asset_name: RuneLaenenTwoFactorAuth.zip
                    asset_content_type: application/zip
